---
- name: Install nginx
  yum:
    name: nginx
    state: latest
- name: Copy nginx files
  copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify: Restart Nginx
