---
- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - java-1.8.0-openjdk

- name: install jmespath using pip
  pip:
    name: jmespath 
