- name: Upgrade all packages
  yum:
    name: "*"
    state: latest
    exclude: kernel*
  
- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - java-1.8.0-openjdk
      - perl
      - rsync
      - ruby
      - tar
      - zip
